//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMQPresentacion.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jmqws.inversiones.jmq.com/", ConfigurationName="UsuarioWS.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/UsuarioWS/helloRequest", ReplyAction="http://jmqws.inversiones.jmq.com/UsuarioWS/helloResponse")]
        JMQPresentacion.UsuarioWS.helloResponse hello(JMQPresentacion.UsuarioWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/UsuarioWS/helloRequest", ReplyAction="http://jmqws.inversiones.jmq.com/UsuarioWS/helloResponse")]
        System.Threading.Tasks.Task<JMQPresentacion.UsuarioWS.helloResponse> helloAsync(JMQPresentacion.UsuarioWS.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        public JMQPresentacion.UsuarioWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(JMQPresentacion.UsuarioWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        public JMQPresentacion.UsuarioWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(JMQPresentacion.UsuarioWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : JMQPresentacion.UsuarioWS.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<JMQPresentacion.UsuarioWS.UsuarioWS>, JMQPresentacion.UsuarioWS.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.UsuarioWS.helloResponse JMQPresentacion.UsuarioWS.UsuarioWS.hello(JMQPresentacion.UsuarioWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            JMQPresentacion.UsuarioWS.helloRequest inValue = new JMQPresentacion.UsuarioWS.helloRequest();
            inValue.Body = new JMQPresentacion.UsuarioWS.helloRequestBody();
            inValue.Body.name = name;
            JMQPresentacion.UsuarioWS.helloResponse retVal = ((JMQPresentacion.UsuarioWS.UsuarioWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.UsuarioWS.helloResponse> JMQPresentacion.UsuarioWS.UsuarioWS.helloAsync(JMQPresentacion.UsuarioWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.UsuarioWS.helloResponse> helloAsync(string name) {
            JMQPresentacion.UsuarioWS.helloRequest inValue = new JMQPresentacion.UsuarioWS.helloRequest();
            inValue.Body = new JMQPresentacion.UsuarioWS.helloRequestBody();
            inValue.Body.name = name;
            return ((JMQPresentacion.UsuarioWS.UsuarioWS)(this)).helloAsync(inValue);
        }
    }
}
