//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMQPresentacion.JMQWSPC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jmqws.inversiones.jmq.com/", ConfigurationName="JMQWSPC.ProductoCotizacionWS")]
    public interface ProductoCotizacionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/helloRequest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JMQPresentacion.JMQWSPC.helloResponse hello(JMQPresentacion.JMQWSPC.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/helloRequest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/helloResponse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.helloResponse> helloAsync(JMQPresentacion.JMQWSPC.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductoCotizacionReq" +
            "uest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductoCotizacionRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JMQPresentacion.JMQWSPC.listarProductoCotizacionResponse listarProductoCotizacion(JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductoCotizacionReq" +
            "uest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductoCotizacionRes" +
            "ponse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.listarProductoCotizacionResponse> listarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/EliminarProductoCotizacionR" +
            "equest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/EliminarProductoCotizacionR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JMQPresentacion.JMQWSPC.EliminarProductoCotizacionResponse EliminarProductoCotizacion(JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/EliminarProductoCotizacionR" +
            "equest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/EliminarProductoCotizacionR" +
            "esponse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.EliminarProductoCotizacionResponse> EliminarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarProductoCotizacio" +
            "nRequest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarProductoCotizacio" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionResponse ActualizarProductoCotizacion(JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarProductoCotizacio" +
            "nRequest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarProductoCotizacio" +
            "nResponse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionResponse> ActualizarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarPrecioProdCotiReq" +
            "uest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarPrecioProdCotiRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiResponse ActualizarPrecioProdCoti(JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarPrecioProdCotiReq" +
            "uest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/ActualizarPrecioProdCotiRes" +
            "ponse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiResponse> ActualizarPrecioProdCotiAsync(JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/RegistrarPrecioProdCotiRequ" +
            "est", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/RegistrarPrecioProdCotiResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiResponse RegistrarPrecioProdCoti(JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/RegistrarPrecioProdCotiRequ" +
            "est", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/RegistrarPrecioProdCotiResp" +
            "onse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiResponse> RegistrarPrecioProdCotiAsync(JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductosPorCotizacio" +
            "nRequest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductosPorCotizacio" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JMQPresentacion.JMQWSPC.listarProductosPorCotizacionResponse listarProductosPorCotizacion(JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductosPorCotizacio" +
            "nRequest", ReplyAction="http://jmqws.inversiones.jmq.com/ProductoCotizacionWS/listarProductosPorCotizacio" +
            "nResponse")]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.listarProductosPorCotizacionResponse> listarProductosPorCotizacionAsync(JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jmqws.inversiones.jmq.com/")]
    public partial class productoCotizacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private string descripcionField;
        
        private int fid_cotizacionField;
        
        private int idField;
        
        private double precioCotizadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int fid_cotizacion {
            get {
                return this.fid_cotizacionField;
            }
            set {
                this.fid_cotizacionField = value;
                this.RaisePropertyChanged("fid_cotizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precioCotizado {
            get {
                return this.precioCotizadoField;
            }
            set {
                this.precioCotizadoField = value;
                this.RaisePropertyChanged("precioCotizado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductoCotizacion", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class listarProductoCotizacionRequest {
        
        public listarProductoCotizacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductoCotizacionResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class listarProductoCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JMQPresentacion.JMQWSPC.productoCotizacion[] @return;
        
        public listarProductoCotizacionResponse() {
        }
        
        public listarProductoCotizacionResponse(JMQPresentacion.JMQWSPC.productoCotizacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarProductoCotizacion", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class EliminarProductoCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public EliminarProductoCotizacionRequest() {
        }
        
        public EliminarProductoCotizacionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarProductoCotizacionResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class EliminarProductoCotizacionResponse {
        
        public EliminarProductoCotizacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProductoCotizacion", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class ActualizarProductoCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JMQPresentacion.JMQWSPC.productoCotizacion arg0;
        
        public ActualizarProductoCotizacionRequest() {
        }
        
        public ActualizarProductoCotizacionRequest(JMQPresentacion.JMQWSPC.productoCotizacion arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProductoCotizacionResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class ActualizarProductoCotizacionResponse {
        
        public ActualizarProductoCotizacionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarPrecioProdCoti", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class ActualizarPrecioProdCotiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JMQPresentacion.JMQWSPC.productoCotizacion arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        public ActualizarPrecioProdCotiRequest() {
        }
        
        public ActualizarPrecioProdCotiRequest(JMQPresentacion.JMQWSPC.productoCotizacion arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarPrecioProdCotiResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class ActualizarPrecioProdCotiResponse {
        
        public ActualizarPrecioProdCotiResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarPrecioProdCoti", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class RegistrarPrecioProdCotiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JMQPresentacion.JMQWSPC.productoCotizacion arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        public RegistrarPrecioProdCotiRequest() {
        }
        
        public RegistrarPrecioProdCotiRequest(JMQPresentacion.JMQWSPC.productoCotizacion arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarPrecioProdCotiResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class RegistrarPrecioProdCotiResponse {
        
        public RegistrarPrecioProdCotiResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorCotizacion", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class listarProductosPorCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarProductosPorCotizacionRequest() {
        }
        
        public listarProductosPorCotizacionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorCotizacionResponse", WrapperNamespace="http://jmqws.inversiones.jmq.com/", IsWrapped=true)]
    public partial class listarProductosPorCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jmqws.inversiones.jmq.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JMQPresentacion.JMQWSPC.productoCotizacion[] @return;
        
        public listarProductosPorCotizacionResponse() {
        }
        
        public listarProductosPorCotizacionResponse(JMQPresentacion.JMQWSPC.productoCotizacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoCotizacionWSChannel : JMQPresentacion.JMQWSPC.ProductoCotizacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoCotizacionWSClient : System.ServiceModel.ClientBase<JMQPresentacion.JMQWSPC.ProductoCotizacionWS>, JMQPresentacion.JMQWSPC.ProductoCotizacionWS {
        
        public ProductoCotizacionWSClient() {
        }
        
        public ProductoCotizacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoCotizacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoCotizacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoCotizacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.helloResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.hello(JMQPresentacion.JMQWSPC.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            JMQPresentacion.JMQWSPC.helloRequest inValue = new JMQPresentacion.JMQWSPC.helloRequest();
            inValue.name = name;
            JMQPresentacion.JMQWSPC.helloResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.helloResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.helloAsync(JMQPresentacion.JMQWSPC.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.helloResponse> helloAsync(string name) {
            JMQPresentacion.JMQWSPC.helloRequest inValue = new JMQPresentacion.JMQWSPC.helloRequest();
            inValue.name = name;
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.listarProductoCotizacionResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.listarProductoCotizacion(JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest request) {
            return base.Channel.listarProductoCotizacion(request);
        }
        
        public JMQPresentacion.JMQWSPC.productoCotizacion[] listarProductoCotizacion() {
            JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest();
            JMQPresentacion.JMQWSPC.listarProductoCotizacionResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).listarProductoCotizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.listarProductoCotizacionResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.listarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest request) {
            return base.Channel.listarProductoCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.listarProductoCotizacionResponse> listarProductoCotizacionAsync() {
            JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.listarProductoCotizacionRequest();
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).listarProductoCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.EliminarProductoCotizacionResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.EliminarProductoCotizacion(JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest request) {
            return base.Channel.EliminarProductoCotizacion(request);
        }
        
        public void EliminarProductoCotizacion(int arg0) {
            JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest();
            inValue.arg0 = arg0;
            JMQPresentacion.JMQWSPC.EliminarProductoCotizacionResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).EliminarProductoCotizacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.EliminarProductoCotizacionResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.EliminarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest request) {
            return base.Channel.EliminarProductoCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.EliminarProductoCotizacionResponse> EliminarProductoCotizacionAsync(int arg0) {
            JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.EliminarProductoCotizacionRequest();
            inValue.arg0 = arg0;
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).EliminarProductoCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.ActualizarProductoCotizacion(JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest request) {
            return base.Channel.ActualizarProductoCotizacion(request);
        }
        
        public void ActualizarProductoCotizacion(JMQPresentacion.JMQWSPC.productoCotizacion arg0) {
            JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest();
            inValue.arg0 = arg0;
            JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).ActualizarProductoCotizacion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.ActualizarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest request) {
            return base.Channel.ActualizarProductoCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionResponse> ActualizarProductoCotizacionAsync(JMQPresentacion.JMQWSPC.productoCotizacion arg0) {
            JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.ActualizarProductoCotizacionRequest();
            inValue.arg0 = arg0;
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).ActualizarProductoCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.ActualizarPrecioProdCoti(JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest request) {
            return base.Channel.ActualizarPrecioProdCoti(request);
        }
        
        public void ActualizarPrecioProdCoti(JMQPresentacion.JMQWSPC.productoCotizacion arg0, double arg1) {
            JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest inValue = new JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).ActualizarPrecioProdCoti(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.ActualizarPrecioProdCotiAsync(JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest request) {
            return base.Channel.ActualizarPrecioProdCotiAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiResponse> ActualizarPrecioProdCotiAsync(JMQPresentacion.JMQWSPC.productoCotizacion arg0, double arg1) {
            JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest inValue = new JMQPresentacion.JMQWSPC.ActualizarPrecioProdCotiRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).ActualizarPrecioProdCotiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.RegistrarPrecioProdCoti(JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest request) {
            return base.Channel.RegistrarPrecioProdCoti(request);
        }
        
        public void RegistrarPrecioProdCoti(JMQPresentacion.JMQWSPC.productoCotizacion arg0, double arg1) {
            JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest inValue = new JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).RegistrarPrecioProdCoti(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.RegistrarPrecioProdCotiAsync(JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest request) {
            return base.Channel.RegistrarPrecioProdCotiAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiResponse> RegistrarPrecioProdCotiAsync(JMQPresentacion.JMQWSPC.productoCotizacion arg0, double arg1) {
            JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest inValue = new JMQPresentacion.JMQWSPC.RegistrarPrecioProdCotiRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).RegistrarPrecioProdCotiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JMQPresentacion.JMQWSPC.listarProductosPorCotizacionResponse JMQPresentacion.JMQWSPC.ProductoCotizacionWS.listarProductosPorCotizacion(JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest request) {
            return base.Channel.listarProductosPorCotizacion(request);
        }
        
        public JMQPresentacion.JMQWSPC.productoCotizacion[] listarProductosPorCotizacion(int arg0) {
            JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest();
            inValue.arg0 = arg0;
            JMQPresentacion.JMQWSPC.listarProductosPorCotizacionResponse retVal = ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).listarProductosPorCotizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.listarProductosPorCotizacionResponse> JMQPresentacion.JMQWSPC.ProductoCotizacionWS.listarProductosPorCotizacionAsync(JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest request) {
            return base.Channel.listarProductosPorCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMQPresentacion.JMQWSPC.listarProductosPorCotizacionResponse> listarProductosPorCotizacionAsync(int arg0) {
            JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest inValue = new JMQPresentacion.JMQWSPC.listarProductosPorCotizacionRequest();
            inValue.arg0 = arg0;
            return ((JMQPresentacion.JMQWSPC.ProductoCotizacionWS)(this)).listarProductosPorCotizacionAsync(inValue);
        }
    }
}
