//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Admin.Usuarios
{


    public partial class Usuarios
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;
        /// <summary>
        /// Control txtNombreUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombreUsuario;

        /// <summary>
        /// Control txtCorreo.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        /// <summary>
        /// Control txtRazonSocial.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;

        /// <summary>
        /// Control txtDireccion.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        /// <summary>
        /// Control txtRUC.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRUC;

        /// <summary>
        /// Control btnGuardarUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarUsuario;


    }
}
