//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Admin.Pagos
{


    public partial class Pagos
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gvPagos;

        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroTipo;

        protected global::System.Web.UI.WebControls.TextBox txtFechaPago;
        protected global::System.Web.UI.WebControls.TextBox txtMonto;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtDNI;

        protected global::System.Web.UI.WebControls.TextBox txtRUC;
        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        protected global::System.Web.UI.WebControls.TextBox txtFechaEmision;

        protected global::System.Web.UI.WebControls.DropDownList ddlTipoPago;

        protected global::System.Web.UI.WebControls.Button btnGuardarPago;
    }
}
