//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Admin.Cotizaciones
{


    public partial class Cotizaciones
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gvCotizaciones;
        protected global::System.Web.UI.WebControls.TextBox txtEstado;
        protected global::System.Web.UI.WebControls.Button btnGuardarCotizacion;
        protected global::System.Web.UI.WebControls.Panel pnlModalAgregar;
        protected global::System.Web.UI.WebControls.TextBox txtNombreUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.TextBox txtRUC;


    }
}
